A Guide to Outbound Open Source Software
lfapac-open-source-evangelist/todogroup.org pull request #20
Opened 2024-03-21 16:46 UTC by lichenmao

Need review.

2024-04-22 10:40 UTC, node commented
不属于本PR 范围的 content/zh-CN/guides/ospo-simple-faq.md   文件被修改了，建议回退，否则提交后会覆盖其他译者的翻译。

2024-04-22 10:40 UTC, node commented
由于是基于已有的英文文件来翻译，因为无需保留中英对照，仅保留中文即可；markdown相关的语法标记无需翻译，否则会影响编译和排版布局。

2024-04-22 10:41 UTC, node requested changes
删除英文，仅保留中文。

2024-06-20 12:15 UTC, terizhao commented
@lichenmao Please address comments. Thanks.

2024-06-23 14:35 UTC, lichenmao commented
> @lichenmao Please address comments. Thanks.

OK, I have removed the English.

2024-07-01 09:38 UTC, node approved these changes
LGTM

2024-07-01 09:39 UTC, node commented
本PR包含了对于其他文件的更新，请确保不会与其他PR相互覆盖；否则，建议在本PR中放弃对于其他文件的更新提交。

2024-07-04 12:13 UTC, merged