Building an Inclusive Open Source Community
lfapac-open-source-evangelist/todogroup.org pull request #22
Opened 2024-04-04 01:04 UTC by lichenmao

Need Review.

2024-04-22 10:28 UTC, node requested changes
请注意，本次翻译的任务是TODO Group官网的指南内容，所以翻译稿仅需提供中文版即可，英文需删除。 同时，涉及Markdown语法相关标记及属性名称不能翻译，会影响最终的编译和排版。

2024-04-22 10:28 UTC, node commented on content/zh-CN/guides/diversity-inclusion.md
> +标题: 打造一个包容性的开源社区
这里的 title: 不能翻译

2024-04-22 10:30 UTC, node commented on content/zh-CN/guides/diversity-inclusion.md
> +麦肯锡公司（Mckinsey & Company）在 2017 年发布的一份[报告](https://www.mckinsey.com/business-functions/organization/our-insights/delivering-through-diversity?cid=soc-web)中发现，执行团队中性别多样性最高的前 25% 的公司比后 25% 的公司高出 15% 的可
> 执行团队中性别多样性最高的前 25% 的公司比后 25% 的公司高出 15% 的可能性获得平均水平之上的盈利，

执行团队中性别多样性最高的前 25% 的公司比后 25% 的公司，在获得平均水平之上的盈利方面高出 15% 的可能性。

2024-04-22 10:32 UTC, node commented on content/zh-CN/guides/diversity-inclusion.md
> +* 参与会议和面对面会议对经济困难的人来说可能无法实现。
经济弱势群体可能无法出差参加大会和面对面会议。

2024-04-22 10:33 UTC, node commented on content/zh-CN/guides/diversity-inclusion.md
> +* 曾经塑造早期开源社区项目的文化正在
似乎串行了 。

2024-06-20 12:14 UTC, terizhao commented
@lichenmao Please address comments.  Thanks.

2024-08-08 07:55 UTC, node approved these changes
LGTM

2024-08-13 07:00 UTC, merged