Translate content/zh-CN/guides/marketing-open-source-projects.md
lfapac-open-source-evangelist/todogroup.org pull request #24
Opened 2024-04-07 07:40 UTC by hwang37

Fixes todogroup.org#9

2024-04-10 07:51 UTC, node requested changes

2024-04-10 07:51 UTC, node commented on content/zh-CN/guides/marketing-open-source-projects.md
> +title: 营销开源项目
推广开源项目 会更符合中文语境？

2024-04-10 07:51 UTC, node commented on content/zh-CN/guides/marketing-open-source-projects.md
> +市场营销和代码一样，对任何开源项目的成功至关重要。参与开源项目的组织通过自己的网络来推广项目，从而在项目周围建立可持续发展的生态系统，并发挥重要作用。作为回报，组织可以通过提高项目在社区中的知名度并将自己的品牌与项目联系起来，从这些营销工作中受益。其好处包括：不断增强的项目领导角色、吸引开发人员加入您的组织以及推广您的开源产品和服务。成功的关键是首先要推广项目，并始终秉承开放和透明的开源精神保持
> 从而在项目周围建立

从而围绕项目建立 或 从而以项目为中心建立

2024-04-10 07:51 UTC, node commented on content/zh-CN/guides/marketing-open-source-projects.md
> +> “ ‘只要创造出来，就会有人来用’的观念是完全错误的。充其量，这是个短视和危险的假设借口，它认为不需要付出努力而项目就可以取得成功。” Deirdré Straughan，亚马逊网络服务(AWS) 的开源内容主管，她在两年前的北美开源峰会上的[演讲](https://www.linux.com/news/how-market-open-source-project) 说。“仅仅构建一个软件是
AWS 建议不用翻译了。

2024-04-10 07:51 UTC, node commented on content/zh-CN/guides/marketing-open-source-projects.md
> +## 社区外的活动等
社区外的活动及其他

2024-04-10 07:51 UTC, node commented on content/zh-CN/guides/marketing-open-source-projects.md
> +在社区外进行营销以吸引新人来帮助您完成项目使命也同样重要。进行此类营销的主要形式是各种活动。出席、赞助和演讲都是有效且常见的营销策略。在活动中进行演示是完善你的信息的一种方式，并且可以根据受众量身定制。如果预算允许，您还可以选择举办自己的活动，这提供了将开发者和用户聚集在一处的绝佳机会。有各种各样的活动组织主办公司，或者您也可以与 [Linux基金会]( https://events.linux
> 有各种各样的活动组织主办公司

不太通顺。

2024-04-10 07:51 UTC, node commented on content/zh-CN/guides/marketing-open-source-projects.md
> +开源项目的一个关键目标是防止技术偏离项目中的核心功能，这通常是通过一致性计划和一套品牌和商标指南来实现的。这种兼容性增强了生态系统，给最终用户带来信心，即来自一个环境的数据和解决方案可以在另一个符合条件的环境中以最小的代价正常运行。针对项目的特定商标，一个商标合规计划可以用来鼓励保持与该项目的一致性合规。任何人都可以随心所欲地使用开源项目代码，但如果下游解决方案想要使用项目的一致性合规商标来描述
> 这种兼容性增强了生态系统，

兼容性不太准确，结合上下文可能强调的是  一致性、和谐性

2024-04-12 01:40 UTC, hwang37 commented on content/zh-CN/guides/marketing-open-source-projects.md
> +title: 营销开源项目
Good idea. How about changing to "营销推广"？
In fact, "Marketing" in this article took me a lot of time to put an appropriate Chinese word for translation.

我个人的几个思考：
1. 这里的Marketing，应该是做动名词，第一层含义可以理解为促销，营销，销售活动等。而在本文中可以意译为“推广”第二层的含义。
2. 本文所有的内容都是在围绕“Marketing”这个关键词进行讨论（文中总共出现100个Marketing单词），如果要保持翻译的全文一致性，把全文100个地方都简单替换成“推广”，也不合适，因为会造成整句不通顺。
3. 所以，翻译时需要考虑遵循如下两点：
--  全文尽可能用同一个中文单词进行翻译；（目的：保持文中的单词一致性）
--  但是在此基础上，需要根据不同语句context，进行中文微调；（目的：保持整句阅读的通畅）

几个不同的方案如下：
1. “营销” （直译）
2. “促销” （直译）
3. “推销” （直译） 
4. “销售“ （直译）
5. "推广" （意译）
6. “营销推广”   （意译）

所以这里，也许可以采用”营销推广“。

2024-04-12 01:47 UTC, hwang37 commented on content/zh-CN/guides/marketing-open-source-projects.md
> +市场营销和代码一样，对任何开源项目的成功至关重要。参与开源项目的组织通过自己的网络来推广项目，从而在项目周围建立可持续发展的生态系统，并发挥重要作用。作为回报，组织可以通过提高项目在社区中的知名度并将自己的品牌与项目联系起来，从这些营销工作中受益。其好处包括：不断增强的项目领导角色、吸引开发人员加入您的组织以及推广您的开源产品和服务。成功的关键是首先要推广项目，并始终秉承开放和透明的开源精神保持
Agree.
参与开源项目的组织通过利用自身的网络营销项目，从而围绕项目建立可持续发展的生态系统，组织扮演着重要角色。

2024-04-12 01:47 UTC, hwang37 commented on content/zh-CN/guides/marketing-open-source-projects.md
> +> “ ‘只要创造出来，就会有人来用’的观念是完全错误的。充其量，这是个短视和危险的假设借口，它认为不需要付出努力而项目就可以取得成功。” Deirdré Straughan，亚马逊网络服务(AWS) 的开源内容主管，她在两年前的北美开源峰会上的[演讲](https://www.linux.com/news/how-market-open-source-project) 说。“仅仅构建一个软件是
Sure!

2024-04-12 01:48 UTC, hwang37 commented on content/zh-CN/guides/marketing-open-source-projects.md
> +## 社区外的活动等
Good suggestion!

2024-04-12 01:53 UTC, hwang37 commented on content/zh-CN/guides/marketing-open-source-projects.md
> +在社区外进行营销以吸引新人来帮助您完成项目使命也同样重要。进行此类营销的主要形式是各种活动。出席、赞助和演讲都是有效且常见的营销策略。在活动中进行演示是完善你的信息的一种方式，并且可以根据受众量身定制。如果预算允许，您还可以选择举办自己的活动，这提供了将开发者和用户聚集在一处的绝佳机会。有各种各样的活动组织主办公司，或者您也可以与 [Linux基金会]( https://events.linux
同感，改为：
市面上有很多活动主办公司，您也可以与像 Linux 基金会(https://events.linuxfoundation.org)这样的组织合作举办活动。

2024-04-12 02:10 UTC, hwang37 commented on content/zh-CN/guides/marketing-open-source-projects.md
> +开源项目的一个关键目标是防止技术偏离项目中的核心功能，这通常是通过一致性计划和一套品牌和商标指南来实现的。这种兼容性增强了生态系统，给最终用户带来信心，即来自一个环境的数据和解决方案可以在另一个符合条件的环境中以最小的代价正常运行。针对项目的特定商标，一个商标合规计划可以用来鼓励保持与该项目的一致性合规。任何人都可以随心所欲地使用开源项目代码，但如果下游解决方案想要使用项目的一致性合规商标来描述
修改如下，兼容性（compatibility）和一致性(conformance)还是略有差别。所以修改如下：

一些开源项目的主要目标之一是防止技术功能偏离核心功能集，通常可以通过一致性程序和一套品牌和商标指南来实现。这种一致性增强了生态系统的兼容性，并给最终用户带来信心，即来自一个环境的数据和解决方案可以在另一个兼容的环境中以最小的代价正常运行。

2024-04-12 03:02 UTC, node commented on content/zh-CN/guides/marketing-open-source-projects.md
> +## 开源项目营销的挑战
这里的术语是个挑战，不但要保持单个翻译中一致，还要与其他任务保持一致。

推广和营销在这里几乎是一个意思，所以我建议上下文都统一使用【推广】一词。

2024-04-12 08:11 UTC, hwang37 commented on content/zh-CN/guides/marketing-open-source-projects.md
> +## 开源项目营销的挑战
OK. 已经全部替换成了“推广”

2024-04-16 00:45 UTC, hwang37 commented
@node  Any more comments?

2024-04-16 01:18 UTC, node commented on content/zh-CN/guides/marketing-open-source-projects.md
> +## 社区外的活动及其他
重复了？

2024-04-17 02:19 UTC, hwang37 commented on content/zh-CN/guides/marketing-open-source-projects.md
> +## 社区外的活动及其他
Thanks for the pointing out!
1. Corrected with new PR updates;
2. Also replace "您" with "你" according to comments.

2024-04-17 03:51 UTC, node approved these changes
LGTM

2024-04-22 08:20 UTC, hwang37 commented
@node   Anything else needed from my side? Will you help to merge into main branch?

2024-04-22 08:42 UTC, node commented
> @node Anything else needed from my side? Will you help to merge into main branch?

LGTM. 
Thanks for your translation work. 👋

2024-05-30 03:18 UTC, merged