Update strategy.md
lfapac-open-source-evangelist/todogroup.org pull request #28
Opened 2024-05-08 09:58 UTC by arnuojo

Translation version of strategy.md

2024-05-30 09:30 UTC, node requested changes

2024-05-30 09:30 UTC, node commented on content/zh-CN/guides/strategy.md
> +### Licensing开源许可证
英文可以不要？

2024-06-05 08:47 UTC, arnuojo reviewed
[strategy _2024.6.5.md](https://github.com/user-attachments/files/15581600/strategy._2024.6.5.md)
modified based on node's comments

2024-06-05 08:47 UTC, arnuojo commented on content/zh-CN/guides/strategy.md
> +>“在Salesforce，我们向我们的研发团队分发内部文档，提供关于开源的战略指导和导向。这些导向鼓励开源的创建和使用，让他们毫不含糊地知道，且公司的战略领导者完全支持它。此外，如果我们不希望研发人员使用某些类型的开源许可证，或有其它的一些开源指南，都需要在我们的内部文档中明确。” —— [Ian Varley](https://www.linkedin.com/in/ianvarley/),
+1

2024-06-05 08:47 UTC, arnuojo commented on content/zh-CN/guides/strategy.md
> +在这一点上，创建一个开源项目是无价的。TODO Group的开源指南 [《创建一个开源项目》](https://www.linuxfoundation.org/resources/open-source-guides/creating-an-open-source-program/)  指出："通过创建开源项目办公室OSPO，企业可以是能、简化和组织开源的使用，并使其直接与公司的长期业务计划挂钩
之前是错别字，应该是“”使能“

2024-06-20 12:03 UTC, node approved these changes
LGTM

2024-06-20 12:05 UTC, node commented
Please change your PR's draft status so that others can merge it.

2024-06-20 12:06 UTC, merged