Career
lfapac-open-source-evangelist/todogroup.org pull request #33
Opened 2024-06-23 13:13 UTC by lichenmao

Need Reivew.

2024-06-26 01:08 UTC, sunny0826 commented
@lichenmao This branch has conflicts that must be resolved

2024-07-04 22:57 UTC, zRich requested changes

2024-07-04 22:57 UTC, zRich commented on content/zh-CN/guides/career-development.md
> +* 将职工的多样化职业技能和责任与传统商业术语相对应。
这句话的意思是用传统商业术语解释员工的技能和职责

2024-07-04 22:57 UTC, zRich commented on content/zh-CN/guides/career-development.md
> +随着 OSPO 的职能范围随着时间推移而扩展、收缩或者变化，另一个挑战在于定义特定开源任务的工作范围，因为其中有许多工作超出了传统职位描述的范围，甚至超出了组织本身的范畴。例如，工程师为外部项目贡献代码，或者从事社区管理的人员，或者做其他更注重外部工作的人员。
“另一个挑战在于”，是有这么一个挑战，不是又多了一个，所以不需要“另”

2024-07-04 22:57 UTC, zRich commented on content/zh-CN/guides/career-development.md
> +Norris 解释道：*“我们现在有一个新的工作小组，其重点正是如何帮助提升那些更注重外部工作而非内部工作的人员的工作可见度。其中一些举措实际上是改变谷歌的职业发展阶梯，加入相关语言，真正认可社区贡献和开源工作。”*
这里的 language 翻译成 描述，措辞是不是更加恰当？

2024-07-04 22:57 UTC, zRich commented on content/zh-CN/guides/career-development.md
> +尽管厘清职位头衔是必不可少的第一步，但将这些职位与现有的职位描述相匹配往往是一项让人感到困惑的工作。然而，在许多组织中，专门为开源项目办公室（OSPO）添加新的职位类型通常会成为一个不可逾越的障碍。但这并不意味着这项任务不可能完成。
是关键的第一步，不是“必不可少”

2024-07-12 22:11 UTC, zRich approved these changes
LGTM

2024-07-12 22:12 UTC, merged