translate create-program.md
lfapac-open-source-evangelist/todogroup.org pull request #38
Opened 2024-07-21 11:44 UTC by terizhao

fulfill https://github.com/lfapac-open-source-evangelist/todogroup.org/issues/6 to translate create-program.md

2024-07-22 06:27 UTC, node commented on content/zh-CN/guides/create-program.md
> +* 清晰地传达开源策略给到公司内部和外部
叫作 开源战略 更佳？

2024-07-22 06:28 UTC, node commented on content/zh-CN/guides/create-program.md
> +## 案例：谷歌开源项目
开源项目 在中文里容易产生混淆，建议考虑替换为 开源专项 或 开源计划 等

2024-07-22 06:32 UTC, node commented on content/zh-CN/guides/create-program.md
> +## 最后
结语

2024-07-22 06:33 UTC, node commented on content/zh-CN/guides/create-program.md
> +* [Remy DeCausemaker](https://twitter.com/Remy_D), 开源负责, [Spotify](https://twitter.com/SpotifyEng)
开源负责人

2024-07-24 09:54 UTC, node requested changes

2024-07-24 09:54 UTC, node commented on content/zh-CN/guides/create-program.md
> +## 为什么创建开源办公室
"开源项目办公室”  与 “开源办公室” 或其他叫法，建议尽量在同一个上下文中统一使用，避免混用，引起误会或产生歧义。

2024-07-24 09:54 UTC, node commented on content/zh-CN/guides/create-program.md
> +如今，开源软件被广泛应用，包括从零售到金融再到汽车等各行各业的公司。然而，对于负责运营的高管领导和决策者来说，开源软件并不总是被完全理解。
> 开源软件被广泛应用

开源软件应用广泛

可以尽量减少“被”字句的使用，从而实现更好的中文翻译效果。

2024-07-28 12:34 UTC, terizhao commented on content/zh-CN/guides/create-program.md
> +* 清晰地传达开源策略给到公司内部和外部
好的。

2024-07-28 12:36 UTC, terizhao commented on content/zh-CN/guides/create-program.md
> +* [Remy DeCausemaker](https://twitter.com/Remy_D), 开源负责, [Spotify](https://twitter.com/SpotifyEng)
打漏了。已改正。

2024-07-30 03:19 UTC, terizhao commented on content/zh-CN/guides/create-program.md
> +## 案例：谷歌开源项目
这个应该也该了。

2024-07-30 05:36 UTC, terizhao commented on content/zh-CN/guides/create-program.md
> +如今，开源软件被广泛应用，包括从零售到金融再到汽车等各行各业的公司。然而，对于负责运营的高管领导和决策者来说，开源软件并不总是被完全理解。
好的。

2024-07-30 06:00 UTC, terizhao commented
I did double check on translation for open source program and open source project. Please review it again.

2024-08-08 07:31 UTC, node requested changes

2024-08-08 07:31 UTC, node commented on content/zh-CN/guides/create-program.md
> +## 项目结构
组织架构

2024-08-08 07:31 UTC, node commented on content/zh-CN/guides/create-program.md
>  ### Others
删除英文原文

2024-08-13 07:36 UTC, node approved these changes
LGTM

2024-08-13 07:36 UTC, merged